# -*- coding: utf-8 -*-
"""Joint-Encryption-Steganography-CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uxy4Z9KipYM3Tv6wbjNWDgZfgTzLB9Lb
"""

# -*- coding: utf-8 -*-
"""DeepCrypto_STL10_Enhanced_Analysis.ipynb

Enhanced DeepCrypto implementation with improved resolution and training stability.
WITH GOOGLE DRIVE SAVING SUPPORT
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
import math
from skimage.metrics import structural_similarity as ssim
import os
from datetime import datetime
import seaborn as sns
from scipy import stats
import pandas as pd
from PIL import Image
import cv2
import glob
import torch.nn.functional as F

# ✅ GOOGLE DRIVE INTEGRATION
from google.colab import drive
drive.mount('/content/drive')

# Set random seeds for reproducibility
torch.manual_seed(42)
np.random.seed(42)

# Device configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Enhanced styling for plots
plt.rcParams['figure.figsize'] = [12, 8]
plt.rcParams['font.size'] = 12
sns.set_style("whitegrid")

"""## Enhanced Data Loading with Better Resolution"""

# Improved Hyperparameters for Better Resolution
BATCH_SIZE = 16  # Reduced for higher resolution
IMAGE_SIZE = 128  # Increased from 96 to 128 for better quality
NUM_EPOCHS = 50
LR = 1e-4
LAMBDA_COVER = 1.0
LAMBDA_SECRET = 5.0

# Enhanced transformations with better augmentation
transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.RandomHorizontalFlip(p=0.3),
    transforms.RandomRotation(degrees=5),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
])

# Load STL-10 dataset
train_set = torchvision.datasets.STL10(root='./data', split='train',
                                      download=True, transform=transform)
test_set = torchvision.datasets.STL10(root='./data', split='test',
                                     download=True, transform=transform)

# Data loaders
train_loader = DataLoader(train_set, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
test_loader = DataLoader(test_set, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

# Class names
classes = ('airplane', 'bird', 'car', 'cat', 'deer',
           'dog', 'horse', 'monkey', 'ship', 'truck')

print(f"Dataset loaded: {len(train_set)} training, {len(test_set)} test images")
print(f"Image size: {IMAGE_SIZE}x{IMAGE_SIZE}")

"""## Enhanced Model Architecture with Fixed Skip Connections"""

class ResidualBlock(nn.Module):
    """Improved residual block with better gradient flow"""
    def __init__(self, in_channels, out_channels, stride=1):
        super(ResidualBlock, self).__init__()

        self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=3,
                              stride=stride, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(out_channels)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3,
                              stride=1, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(out_channels)

        # Shortcut connection
        self.shortcut = nn.Sequential()
        if stride != 1 or in_channels != out_channels:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_channels, out_channels, kernel_size=1,
                         stride=stride, bias=False),
                nn.BatchNorm2d(out_channels)
            )

    def forward(self, x):
        residual = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)

        out += self.shortcut(residual)
        out = self.relu(out)

        return out

class DownBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(DownBlock, self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, 3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )
        self.pool = nn.MaxPool2d(2)

    def forward(self, x):
        x = self.conv(x)
        pooled = self.pool(x)
        return pooled

class UpBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(UpBlock, self).__init__()
        self.up = nn.ConvTranspose2d(in_channels, out_channels, kernel_size=2, stride=2)
        self.conv = nn.Sequential(
            nn.Conv2d(out_channels * 2, out_channels, 3, padding=1),  # *2 for skip connection
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, 3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )

    def forward(self, x, skip):
        x = self.up(x)

        # Handle dimension mismatches with interpolation
        if x.shape != skip.shape:
            x = F.interpolate(x, size=skip.shape[2:], mode='bilinear', align_corners=False)

        # Concatenate skip connection
        x = torch.cat([x, skip], dim=1)
        x = self.conv(x)
        return x

class EnhancedEncoder(nn.Module):
    """Enhanced encoder with proper skip connection handling"""
    def __init__(self, in_channels=6, base_channels=64):
        super(EnhancedEncoder, self).__init__()

        # Initial convolution
        self.initial_conv = nn.Sequential(
            nn.Conv2d(in_channels, base_channels, 3, padding=1),
            nn.BatchNorm2d(base_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(base_channels, base_channels, 3, padding=1),
            nn.BatchNorm2d(base_channels),
            nn.ReLU(inplace=True)
        )

        # Downsampling blocks
        self.down1 = DownBlock(base_channels, base_channels * 2)
        self.down2 = DownBlock(base_channels * 2, base_channels * 4)
        self.down3 = DownBlock(base_channels * 4, base_channels * 8)

        # Upsampling blocks
        self.up1 = UpBlock(base_channels * 8, base_channels * 4)
        self.up2 = UpBlock(base_channels * 4, base_channels * 2)
        self.up3 = UpBlock(base_channels * 2, base_channels)

        # Final convolution
        self.final_conv = nn.Sequential(
            nn.Conv2d(base_channels, 3, 3, padding=1),
            nn.Tanh()
        )

    def forward(self, x):
        # Initial convolution
        x1 = self.initial_conv(x)

        # Downsampling
        x2 = self.down1(x1)
        x3 = self.down2(x2)
        x4 = self.down3(x3)

        # Upsampling with skip connections
        x = self.up1(x4, x3)  # Pass skip connection
        x = self.up2(x, x2)   # Pass skip connection
        x = self.up3(x, x1)   # Pass skip connection

        # Final convolution
        x = self.final_conv(x)
        return x

class EnhancedDecoder(nn.Module):
    """Enhanced decoder with proper skip connection handling"""
    def __init__(self, in_channels=3, base_channels=64):
        super(EnhancedDecoder, self).__init__()

        # Initial convolution
        self.initial_conv = nn.Sequential(
            nn.Conv2d(in_channels, base_channels, 3, padding=1),
            nn.BatchNorm2d(base_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(base_channels, base_channels, 3, padding=1),
            nn.BatchNorm2d(base_channels),
            nn.ReLU(inplace=True)
        )

        # Downsampling blocks
        self.down1 = DownBlock(base_channels, base_channels * 2)
        self.down2 = DownBlock(base_channels * 2, base_channels * 4)
        self.down3 = DownBlock(base_channels * 4, base_channels * 8)

        # Upsampling blocks
        self.up1 = UpBlock(base_channels * 8, base_channels * 4)
        self.up2 = UpBlock(base_channels * 4, base_channels * 2)
        self.up3 = UpBlock(base_channels * 2, base_channels)

        # Final convolution
        self.final_conv = nn.Sequential(
            nn.Conv2d(base_channels, 3, 3, padding=1),
            nn.Tanh()
        )

    def forward(self, x):
        # Initial convolution
        x1 = self.initial_conv(x)

        # Downsampling
        x2 = self.down1(x1)
        x3 = self.down2(x2)
        x4 = self.down3(x3)

        # Upsampling with skip connections
        x = self.up1(x4, x3)
        x = self.up2(x, x2)
        x = self.up3(x, x1)

        # Final convolution
        x = self.final_conv(x)
        return x

class EnhancedKeyMixer(nn.Module):
    """Improved KeyMixer with adaptive transformation"""
    def __init__(self, channels=3):
        super(EnhancedKeyMixer, self).__init__()

        # Adaptive transformation network
        self.transformation = nn.Sequential(
            nn.Conv2d(channels, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.Conv2d(64, channels, kernel_size=3, padding=1),
            nn.Tanh()  # Better than Sigmoid for transformation
        )

        # Learnable parameters
        self.alpha = nn.Parameter(torch.tensor(0.1))
        self.beta = nn.Parameter(torch.tensor(0.1))

    def forward(self, cover, secret):
        # Transform the secret
        transformed_secret = self.transformation(secret)

        # Adaptive mixing
        mixed_secret = self.alpha * transformed_secret + self.beta * secret

        # Concatenate with cover
        combined = torch.cat([cover, mixed_secret], dim=1)
        return combined

# Create enhanced models
encoder = EnhancedEncoder().to(device)
decoder = EnhancedDecoder().to(device)
mixer = EnhancedKeyMixer().to(device)

print(f"Encoder parameters: {sum(p.numel() for p in encoder.parameters()):,}")
print(f"Decoder parameters: {sum(p.numel() for p in decoder.parameters()):,}")
print(f"Mixer parameters: {sum(p.numel() for p in mixer.parameters()):,}")

"""## Enhanced Loss Functions with Fast SSIM"""

# Define loss functions
mse_loss = nn.MSELoss()

# Fast SSIM implementation (GPU compatible)
class FastSSIMLoss(nn.Module):
    def __init__(self, window_size=11, channel=3):
        super(FastSSIMLoss, self).__init__()
        self.window_size = window_size
        self.channel = channel
        self.window = self.create_window(window_size, channel)

    def create_window(self, window_size, channel):
        def gaussian(window_size, sigma):
            gauss = torch.Tensor([math.exp(-(x - window_size//2)**2/float(2*sigma**2))
                                for x in range(window_size)])
            return gauss/gauss.sum()

        _1D_window = gaussian(window_size, 1.5).unsqueeze(1)
        _2D_window = _1D_window.mm(_1D_window.t()).float().unsqueeze(0).unsqueeze(0)
        window = _2D_window.expand(channel, 1, window_size, window_size).contiguous()
        return window

    def forward(self, img1, img2):
        if self.window.device != img1.device:
            self.window = self.window.to(img1.device)

        mu1 = torch.nn.functional.conv2d(img1, self.window, padding=self.window_size//2, groups=self.channel)
        mu2 = torch.nn.functional.conv2d(img2, self.window, padding=self.window_size//2, groups=self.channel)

        mu1_sq = mu1.pow(2)
        mu2_sq = mu2.pow(2)
        mu1_mu2 = mu1 * mu2

        sigma1_sq = torch.nn.functional.conv2d(img1*img1, self.window, padding=self.window_size//2, groups=self.channel) - mu1_sq
        sigma2_sq = torch.nn.functional.conv2d(img2*img2, self.window, padding=self.window_size//2, groups=self.channel) - mu2_sq
        sigma12 = torch.nn.functional.conv2d(img1*img2, self.window, padding=self.window_size//2, groups=self.channel) - mu1_mu2

        C1 = 0.01**2
        C2 = 0.03**2

        ssim_map = ((2*mu1_mu2 + C1)*(2*sigma12 + C2)) / ((mu1_sq + mu2_sq + C1)*(sigma1_sq + sigma2_sq + C2))

        return 1 - ssim_map.mean()

fast_ssim_loss = FastSSIMLoss().to(device)

# Enhanced combined loss function
def enhanced_combined_loss(cover, container, secret, recovered, lambda_cover, lambda_secret):
    # MSE components
    mse_cover = mse_loss(container, cover)
    mse_secret = mse_loss(recovered, secret)

    # Fast SSIM components
    ssim_cover = fast_ssim_loss(container, cover)
    ssim_secret = fast_ssim_loss(recovered, secret)

    # Combined losses with better weighting
    loss_cover = 0.6 * mse_cover + 0.4 * ssim_cover
    loss_secret = 0.6 * mse_secret + 0.4 * ssim_secret

    # Total loss
    total_loss = lambda_cover * loss_cover + lambda_secret * loss_secret

    return total_loss, loss_cover, loss_secret, mse_cover, mse_secret, ssim_cover, ssim_secret

# Enhanced evaluation metrics
def calculate_psnr(img1, img2):
    mse = torch.mean((img1 - img2) ** 2)
    if mse == 0:
        return 100
    return 20 * torch.log10(1.0 / torch.sqrt(mse))

def calculate_ssim_batch(img1, img2):
    """Calculate SSIM for entire batch using fast method"""
    ssim_values = []
    batch_size = img1.size(0)

    for i in range(batch_size):
        img1_np = img1[i].cpu().detach().numpy().transpose(1, 2, 0)
        img2_np = img2[i].cpu().detach().numpy().transpose(1, 2, 0)

        # Handle different image sizes
        min_size = min(img1_np.shape[0], img1_np.shape[1],
                      img2_np.shape[0], img2_np.shape[1])
        win_size = min(7, min_size)  # Ensure window size is appropriate

        ssim_val = ssim(img1_np, img2_np, channel_axis=2,
                       data_range=1.0, win_size=win_size)
        ssim_values.append(ssim_val)

    return np.mean(ssim_values)

"""## Enhanced Security Analysis"""

def enhanced_security_analysis(cover, container, secret, recovered):
    """Comprehensive security analysis with better metrics"""

    def calculate_entropy(image):
        # Convert to grayscale for entropy calculation
        if image.shape[0] == 3:  # RGB
            image_gray = 0.2989 * image[0] + 0.5870 * image[1] + 0.1140 * image[2]
        else:
            image_gray = image[0]

        # Calculate histogram
        hist = torch.histc(image_gray, bins=256, min=0, max=1)
        hist = hist[hist > 0]  # Remove zero bins
        prob = hist / hist.sum()
        entropy = -torch.sum(prob * torch.log2(prob + 1e-8))
        return entropy.item()

    def calculate_correlation(img1, img2):
        flat1 = img1.contiguous().view(-1)
        flat2 = img2.contiguous().view(-1)
        correlation = torch.corrcoef(torch.stack([flat1, flat2]))[0, 1]
        return correlation.item() if not torch.isnan(correlation) else 1.0

    def calculate_npcr_uaci(img1, img2):
        diff = torch.abs(img1 - img2)
        npcr = torch.mean((diff > 0.01).float()).item() * 100
        uaci = torch.mean(diff).item() * 100
        return npcr, uaci

    def calculate_histogram_similarity(img1, img2):
        hist1 = torch.histc(img1, bins=256, min=0, max=1)
        hist2 = torch.histc(img2, bins=256, min=0, max=1)
        # Normalize histograms
        hist1 = hist1 / hist1.sum()
        hist2 = hist2 / hist2.sum()
        # Calculate histogram intersection
        intersection = torch.min(hist1, hist2).sum().item()
        return intersection

    results = {}

    # Cover vs Container analysis
    results['cover_entropy'] = calculate_entropy(cover)
    results['container_entropy'] = calculate_entropy(container)
    results['cover_container_correlation'] = calculate_correlation(cover, container)
    results['npcr'], results['uaci'] = calculate_npcr_uaci(cover, container)
    results['histogram_similarity'] = calculate_histogram_similarity(cover, container)

    # Secret vs Recovered analysis
    results['secret_recovered_psnr'] = calculate_psnr(secret, recovered).item()
    results['secret_recovered_ssim'] = calculate_ssim_batch(secret.unsqueeze(0), recovered.unsqueeze(0))

    return results

"""## Enhanced Training Setup with GOOGLE DRIVE SAVING"""

# ✅ Create directories in Google Drive
drive_base_dir = "/content/drive/MyDrive/deepcrypto_results"
local_base_dir = "/content/deepcrypto_results"

# Create both local and drive directories
os.makedirs(drive_base_dir, exist_ok=True)
os.makedirs(local_base_dir, exist_ok=True)

# Create timestamp for this run
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
save_dir_local = os.path.join(local_base_dir, f"deepcrypto_enhanced_{timestamp}")
save_dir_drive = os.path.join(drive_base_dir, f"deepcrypto_enhanced_{timestamp}")

os.makedirs(save_dir_local, exist_ok=True)
os.makedirs(save_dir_drive, exist_ok=True)

print(f"📁 Local save directory: {save_dir_local}")
print(f"📁 Google Drive save directory: {save_dir_drive}")

# Enhanced training history
history = {
    'epoch': [],
    'train_loss': [], 'cover_loss': [], 'secret_loss': [],
    'val_loss': [], 'val_cover_loss': [], 'val_secret_loss': [],
    'psnr_cover': [], 'psnr_secret': [], 'ssim_cover': [], 'ssim_secret': [],
    'mse_cover': [], 'mse_secret': [], 'learning_rate': []
}

security_metrics = []

# Enhanced optimizer with better settings
optimizer = optim.AdamW(
    list(encoder.parameters()) + list(decoder.parameters()) + list(mixer.parameters()),
    lr=LR, betas=(0.9, 0.999), weight_decay=1e-4
)

# Enhanced scheduler
scheduler = optim.lr_scheduler.OneCycleLR(
    optimizer, max_lr=LR*10, epochs=NUM_EPOCHS,
    steps_per_epoch=len(train_loader), pct_start=0.1
)

# ✅ Enhanced saving function for Google Drive
def save_to_drive(file_path, drive_path):
    """Copy files from local to Google Drive"""
    try:
        # Copy file to drive
        os.system(f"cp '{file_path}' '{drive_path}'")
        return True
    except Exception as e:
        print(f"❌ Error saving to drive: {e}")
        return False

def save_checkpoint(epoch, is_best=False):
    """Save checkpoint to both local and Google Drive"""
    checkpoint = {
        'epoch': epoch,
        'encoder_state_dict': encoder.state_dict(),
        'decoder_state_dict': decoder.state_dict(),
        'mixer_state_dict': mixer.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'scheduler_state_dict': scheduler.state_dict(),
        'loss': best_val_loss,
        'history': history,
        'security_metrics': security_metrics
    }

    # Save locally
    local_path = os.path.join(save_dir_local, f'checkpoint_epoch_{epoch}.pth')
    torch.save(checkpoint, local_path)

    # Save to Google Drive
    drive_path = os.path.join(save_dir_drive, f'checkpoint_epoch_{epoch}.pth')
    if save_to_drive(local_path, drive_path):
        print(f"💾 Checkpoint saved to Google Drive: epoch {epoch}")

    # Save best model separately
    if is_best:
        best_local = os.path.join(save_dir_local, 'best_model.pth')
        best_drive = os.path.join(save_dir_drive, 'best_model.pth')
        torch.save(checkpoint, best_local)
        save_to_drive(best_local, best_drive)
        print("🏆 BEST model saved to Google Drive!")

    # Save latest checkpoint
    latest_local = os.path.join(save_dir_local, 'latest_checkpoint.pth')
    latest_drive = os.path.join(save_dir_drive, 'latest_checkpoint.pth')
    torch.save(checkpoint, latest_local)
    save_to_drive(latest_local, latest_drive)

"""## Enhanced Visualization Functions"""

def create_comprehensive_visualization(cover, container, secret, recovered, epoch, save_dir):
    """Create comprehensive visualization of results"""

    fig = plt.figure(figsize=(20, 16))

    for i in range(min(4, cover.size(0))):  # Handle small batch sizes
        # Original Cover
        plt.subplot(4, 6, i*6 + 1)
        plt.imshow(cover[i].permute(1, 2, 0).cpu().numpy())
        plt.title(f'Cover Image {i+1}')
        plt.axis('off')

        # Container Image
        plt.subplot(4, 6, i*6 + 2)
        plt.imshow(container[i].permute(1, 2, 0).cpu().numpy())
        plt.title(f'Container (PSNR: {calculate_psnr(cover[i], container[i]):.2f} dB)')
        plt.axis('off')

        # Difference Map (Cover vs Container)
        plt.subplot(4, 6, i*6 + 3)
        diff = torch.abs(cover[i] - container[i]).mean(0)
        plt.imshow(diff.cpu().numpy(), cmap='hot', vmin=0, vmax=0.3)
        plt.title(f'Difference Map\nMax diff: {diff.max():.3f}')
        plt.axis('off')
        plt.colorbar(fraction=0.046)

        # Original Secret
        plt.subplot(4, 6, i*6 + 4)
        plt.imshow(secret[i].permute(1, 2, 0).cpu().numpy())
        plt.title(f'Secret Image {i+1}')
        plt.axis('off')

        # Recovered Secret
        plt.subplot(4, 6, i*6 + 5)
        plt.imshow(recovered[i].permute(1, 2, 0).cpu().numpy())
        plt.title(f'Recovered (PSNR: {calculate_psnr(secret[i], recovered[i]):.2f} dB)')
        plt.axis('off')

        # Difference Map (Secret vs Recovered)
        plt.subplot(4, 6, i*6 + 6)
        diff_secret = torch.abs(secret[i] - recovered[i]).mean(0)
        plt.imshow(diff_secret.cpu().numpy(), cmap='hot', vmin=0, vmax=0.3)
        plt.title(f'Secret Difference\nMax diff: {diff_secret.max():.3f}')
        plt.axis('off')
        plt.colorbar(fraction=0.046)

    plt.suptitle(f'DeepCrypto Results - Epoch {epoch}', fontsize=16, y=0.95)
    plt.tight_layout()

    # Save locally
    local_path = os.path.join(save_dir_local, f'comprehensive_results_epoch_{epoch}.png')
    plt.savefig(local_path, dpi=150, bbox_inches='tight')

    # Save to Google Drive
    drive_path = os.path.join(save_dir_drive, f'comprehensive_results_epoch_{epoch}.png')
    save_to_drive(local_path, drive_path)

    plt.close()
    print(f"📊 Visualization saved for epoch {epoch}")

def plot_training_history(history, save_dir):
    """Create comprehensive training history plots"""

    fig, axes = plt.subplots(2, 3, figsize=(18, 12))

    # Loss curves
    axes[0, 0].plot(history['epoch'], history['train_loss'], label='Training Loss', linewidth=2)
    axes[0, 0].plot(history['epoch'], history['val_loss'], label='Validation Loss', linewidth=2)
    axes[0, 0].set_title('Training and Validation Loss')
    axes[0, 0].set_xlabel('Epoch')
    axes[0, 0].set_ylabel('Loss')
    axes[0, 0].legend()
    axes[0, 0].grid(True, alpha=0.3)

    # Component losses
    axes[0, 1].plot(history['epoch'], history['cover_loss'], label='Cover Loss', linewidth=2)
    axes[0, 1].plot(history['epoch'], history['secret_loss'], label='Secret Loss', linewidth=2)
    axes[0, 1].set_title('Component Losses')
    axes[0, 1].set_xlabel('Epoch')
    axes[0, 1].set_ylabel('Loss')
    axes[0, 1].legend()
    axes[0, 1].grid(True, alpha=0.3)

    # PSNR metrics
    axes[0, 2].plot(history['epoch'], history['psnr_cover'], label='Cover PSNR', linewidth=2)
    axes[0, 2].plot(history['epoch'], history['psnr_secret'], label='Secret PSNR', linewidth=2)
    axes[0, 2].set_title('PSNR Metrics')
    axes[0, 2].set_xlabel('Epoch')
    axes[0, 2].set_ylabel('PSNR (dB)')
    axes[0, 2].legend()
    axes[0, 2].grid(True, alpha=0.3)

    # SSIM metrics
    axes[1, 0].plot(history['epoch'], history['ssim_cover'], label='Cover SSIM', linewidth=2)
    axes[1, 0].plot(history['epoch'], history['ssim_secret'], label='Secret SSIM', linewidth=2)
    axes[1, 0].set_title('SSIM Metrics')
    axes[1, 0].set_xlabel('Epoch')
    axes[1, 0].set_ylabel('SSIM')
    axes[1, 0].legend()
    axes[1, 0].grid(True, alpha=0.3)

    # MSE metrics
    axes[1, 1].plot(history['epoch'], history['mse_cover'], label='Cover MSE', linewidth=2)
    axes[1, 1].plot(history['epoch'], history['mse_secret'], label='Secret MSE', linewidth=2)
    axes[1, 1].set_title('MSE Metrics')
    axes[1, 1].set_xlabel('Epoch')
    axes[1, 1].set_ylabel('MSE')
    axes[1, 1].set_yscale('log')
    axes[1, 1].legend()
    axes[1, 1].grid(True, alpha=0.3)

    # Learning rate
    axes[1, 2].plot(history['epoch'], history['learning_rate'], label='Learning Rate', linewidth=2, color='red')
    axes[1, 2].set_title('Learning Rate Schedule')
    axes[1, 2].set_xlabel('Epoch')
    axes[1, 2].set_ylabel('Learning Rate')
    axes[1, 2].set_yscale('log')
    axes[1, 2].grid(True, alpha=0.3)

    plt.tight_layout()

    # Save locally
    local_path = os.path.join(save_dir_local, 'comprehensive_training_history.png')
    plt.savefig(local_path, dpi=150, bbox_inches='tight')

    # Save to Google Drive
    drive_path = os.path.join(save_dir_drive, 'comprehensive_training_history.png')
    save_to_drive(local_path, drive_path)

    plt.close()
    print("📈 Training history plots saved to Google Drive!")

"""## Enhanced Training Loop with AUTO-SAVING"""

# Training loop
best_val_loss = float('inf')
patience_counter = 0
patience = 10  # Early stopping patience

print("Starting Enhanced Training with Google Drive Saving...")
print("=" * 80)

for epoch in range(1, NUM_EPOCHS + 1):
    # Training phase
    encoder.train()
    decoder.train()
    mixer.train()

    train_loss = 0.0
    cover_loss = 0.0
    secret_loss = 0.0
    mse_cover_total = 0.0
    mse_secret_total = 0.0
    num_batches = 0

    progress_bar = tqdm(train_loader, desc=f'Epoch {epoch}/{NUM_EPOCHS}')
    for batch_idx, (images, _) in enumerate(progress_bar):
        images = images.to(device)
        batch_size = images.size(0)

        # Use different images for cover and secret
        idx = torch.randperm(batch_size)
        secret_images = images[idx]

        # Forward pass
        mixed_input = mixer(images, secret_images)
        container = encoder(mixed_input)
        recovered = decoder(container)

        # Calculate loss
        loss, cov_loss, sec_loss, mse_cov, mse_sec, ssim_cov, ssim_sec = enhanced_combined_loss(
            images, container, secret_images, recovered,
            LAMBDA_COVER, LAMBDA_SECRET
        )

        # Backward pass and optimize
        optimizer.zero_grad()
        loss.backward()

        # Gradient clipping for stability
        torch.nn.utils.clip_grad_norm_(
            list(encoder.parameters()) + list(decoder.parameters()) + list(mixer.parameters()),
            max_norm=1.0
        )

        optimizer.step()
        scheduler.step()  # Update learning rate

        # Accumulate losses
        train_loss += loss.item() * batch_size
        cover_loss += cov_loss.item() * batch_size
        secret_loss += sec_loss.item() * batch_size
        mse_cover_total += mse_cov.item() * batch_size
        mse_secret_total += mse_sec.item() * batch_size
        num_batches += batch_size

        # Update progress bar
        progress_bar.set_postfix({
            'Loss': f'{loss.item():.4f}',
            'Cover': f'{cov_loss.item():.4f}',
            'Secret': f'{sec_loss.item():.4f}',
            'LR': f'{scheduler.get_last_lr()[0]:.2e}'
        })

    # Calculate average training losses
    avg_train_loss = train_loss / num_batches
    avg_cover_loss = cover_loss / num_batches
    avg_secret_loss = secret_loss / num_batches
    avg_mse_cover = mse_cover_total / num_batches
    avg_mse_secret = mse_secret_total / num_batches

    # Validation phase
    encoder.eval()
    decoder.eval()
    mixer.eval()

    val_loss = 0.0
    val_cover_loss = 0.0
    val_secret_loss = 0.0
    val_psnr_cover = 0.0
    val_psnr_secret = 0.0
    val_ssim_cover = 0.0
    val_ssim_secret = 0.0
    val_batches = 0

    with torch.no_grad():
        for images, _ in test_loader:
            images = images.to(device)
            batch_size = images.size(0)

            idx = torch.randperm(batch_size)
            secret_images = images[idx]

            mixed_input = mixer(images, secret_images)
            container = encoder(mixed_input)
            recovered = decoder(container)

            loss, cov_loss, sec_loss, _, _, _, _ = enhanced_combined_loss(
                images, container, secret_images, recovered,
                LAMBDA_COVER, LAMBDA_SECRET
            )

            # Calculate metrics
            psnr_cover = calculate_psnr(images, container)
            psnr_secret = calculate_psnr(secret_images, recovered)
            ssim_cover = calculate_ssim_batch(images, container)
            ssim_secret = calculate_ssim_batch(secret_images, recovered)

            val_loss += loss.item() * batch_size
            val_cover_loss += cov_loss.item() * batch_size
            val_secret_loss += sec_loss.item() * batch_size
            val_psnr_cover += psnr_cover.item() * batch_size
            val_psnr_secret += psnr_secret.item() * batch_size
            val_ssim_cover += ssim_cover * batch_size
            val_ssim_secret += ssim_secret * batch_size
            val_batches += batch_size

    # Average validation metrics
    val_loss /= val_batches
    val_cover_loss /= val_batches
    val_secret_loss /= val_batches
    val_psnr_cover /= val_batches
    val_psnr_secret /= val_batches
    val_ssim_cover /= val_batches
    val_ssim_secret /= val_batches

    current_lr = scheduler.get_last_lr()[0]

    # Save history
    history['epoch'].append(epoch)
    history['train_loss'].append(avg_train_loss)
    history['cover_loss'].append(avg_cover_loss)
    history['secret_loss'].append(avg_secret_loss)
    history['val_loss'].append(val_loss)
    history['val_cover_loss'].append(val_cover_loss)
    history['val_secret_loss'].append(val_secret_loss)
    history['psnr_cover'].append(val_psnr_cover)
    history['psnr_secret'].append(val_psnr_secret)
    history['ssim_cover'].append(val_ssim_cover)
    history['ssim_secret'].append(val_ssim_secret)
    history['mse_cover'].append(avg_mse_cover)
    history['mse_secret'].append(avg_mse_secret)
    history['learning_rate'].append(current_lr)

    # Print comprehensive metrics
    print(f'\nEpoch {epoch}/{NUM_EPOCHS}:')
    print(f'Train Loss: {avg_train_loss:.4f} | Cover: {avg_cover_loss:.4f} | Secret: {avg_secret_loss:.4f}')
    print(f'Val Loss: {val_loss:.4f} | Cover: {val_cover_loss:.4f} | Secret: {val_secret_loss:.4f}')
    print(f'PSNR - Cover: {val_psnr_cover:.2f} dB | Secret: {val_psnr_secret:.2f} dB')
    print(f'SSIM - Cover: {val_ssim_cover:.4f} | Secret: {val_ssim_secret:.4f}')
    print(f'Learning Rate: {current_lr:.2e}')

    # Check if best model
    is_best = val_loss < best_val_loss
    if is_best:
        best_val_loss = val_loss
        patience_counter = 0
        print('🔥 New best model!')
    else:
        patience_counter += 1

    # ✅ SAVE CHECKPOINT TO GOOGLE DRIVE (Every epoch)
    save_checkpoint(epoch, is_best)

    # Enhanced visualization every 5 epochs
    if epoch % 5 == 0 or epoch == 1:
        with torch.no_grad():
            test_images, _ = next(iter(test_loader))
            test_images = test_images.to(device)

            idx = torch.randperm(test_images.size(0))
            secret_images = test_images[idx]

            mixed_input = mixer(test_images, secret_images)
            container = encoder(mixed_input)
            recovered = decoder(container)

            # Convert to CPU for visualization
            test_images_cpu = test_images.cpu()
            secret_images_cpu = secret_images.cpu()
            container_cpu = container.cpu()
            recovered_cpu = recovered.cpu()

            create_comprehensive_visualization(
                test_images_cpu[:4], container_cpu[:4],
                secret_images_cpu[:4], recovered_cpu[:4],
                epoch, save_dir_local
            )

        # Plot training history
        plot_training_history(history, save_dir_local)

    # Security analysis every 10 epochs
    if epoch % 10 == 0:
        with torch.no_grad():
            test_images, _ = next(iter(test_loader))
            test_images = test_images.to(device)

            idx = torch.randperm(test_images.size(0))
            secret_images = test_images[idx]

            mixed_input = mixer(test_images, secret_images)
            container = encoder(mixed_input)
            recovered = decoder(container)

            # Analyze first image
            security_result = enhanced_security_analysis(
                test_images[0], container[0], secret_images[0], recovered[0]
            )
            security_result['epoch'] = epoch
            security_metrics.append(security_result)

            print(f"\nSecurity Analysis (Epoch {epoch}):")
            print(f"Cover Entropy: {security_result['cover_entropy']:.3f}")
            print(f"Container Entropy: {security_result['container_entropy']:.3f}")
            print(f"Correlation: {security_result['cover_container_correlation']:.6f}")
            print(f"NPCR: {security_result['npcr']:.2f}% | UACI: {security_result['uaci']:.2f}%")

    # Early stopping check
    if patience_counter >= patience:
        print(f'🛑 Early stopping triggered after {epoch} epochs!')
        break

print('🎉 Training completed!')

"""## Results Analysis and Visualization with GOOGLE DRIVE SAVING"""

print("\n" + "="*80)
print("COMPREHENSIVE RESULTS ANALYSIS")
print("="*80)

# Final evaluation
encoder.eval()
decoder.eval()
mixer.eval()

final_results = {}

with torch.no_grad():
    # Get test batch for final analysis
    test_images, labels = next(iter(test_loader))
    test_images = test_images.to(device)

    idx = torch.randperm(test_images.size(0))
    secret_images = test_images[idx]

    # DeepCrypto results
    mixed_input = mixer(test_images, secret_images)
    container = encoder(mixed_input)
    recovered = decoder(container)

    # Calculate final metrics
    final_psnr_cover = calculate_psnr(test_images, container).item()
    final_psnr_secret = calculate_psnr(secret_images, recovered).item()
    final_ssim_cover = calculate_ssim_batch(test_images, container)
    final_ssim_secret = calculate_ssim_batch(secret_images, recovered)

    final_results = {
        'psnr_cover': final_psnr_cover,
        'psnr_secret': final_psnr_secret,
        'ssim_cover': final_ssim_cover,
        'ssim_secret': final_ssim_secret
    }

# Create final comprehensive visualization
def create_final_analysis_plots(history, security_metrics, final_results, save_dir):
    """Create final comprehensive analysis plots"""

    fig, axes = plt.subplots(2, 3, figsize=(20, 14))

    # Performance metrics over time
    axes[0, 0].plot(history['epoch'], history['psnr_cover'], label='Cover PSNR', linewidth=3, alpha=0.8)
    axes[0, 0].plot(history['epoch'], history['psnr_secret'], label='Secret PSNR', linewidth=3, alpha=0.8)
    axes[0, 0].set_title('PSNR Evolution During Training', fontsize=14, fontweight='bold')
    axes[0, 0].set_xlabel('Epoch')
    axes[0, 0].set_ylabel('PSNR (dB)')
    axes[0, 0].legend()
    axes[0, 0].grid(True, alpha=0.3)

    # SSIM evolution
    axes[0, 1].plot(history['epoch'], history['ssim_cover'], label='Cover SSIM', linewidth=3, alpha=0.8)
    axes[0, 1].plot(history['epoch'], history['ssim_secret'], label='Secret SSIM', linewidth=3, alpha=0.8)
    axes[0, 1].set_title('SSIM Evolution During Training', fontsize=14, fontweight='bold')
    axes[0, 1].set_xlabel('Epoch')
    axes[0, 1].set_ylabel('SSIM')
    axes[0, 1].legend()
    axes[0, 1].grid(True, alpha=0.3)

    # Security metrics
    if security_metrics:
        epochs = [m['epoch'] for m in security_metrics]
        entropy_cover = [m['cover_entropy'] for m in security_metrics]
        entropy_container = [m['container_entropy'] for m in security_metrics]

        axes[0, 2].plot(epochs, entropy_cover, label='Cover Entropy', marker='o', linewidth=2)
        axes[0, 2].plot(epochs, entropy_container, label='Container Entropy', marker='s', linewidth=2)
        axes[0, 2].set_title('Security: Entropy Evolution', fontsize=14, fontweight='bold')
        axes[0, 2].set_xlabel('Epoch')
        axes[0, 2].set_ylabel('Entropy')
        axes[0, 2].legend()
        axes[0, 2].grid(True, alpha=0.3)

    # Final performance summary
    summary_text = f"""
    DeepCrypto Final Performance Summary:

    Image Resolution: {IMAGE_SIZE}x{IMAGE_SIZE}
    Training Epochs: {len(history['epoch'])}

    Cover Image Quality:
    • PSNR: {final_results['psnr_cover']:.2f} dB
    • SSIM: {final_results['ssim_cover']:.4f}

    Secret Recovery Quality:
    • PSNR: {final_results['psnr_secret']:.2f} dB
    • SSIM: {final_results['ssim_secret']:.4f}

    Training Statistics:
    • Final Validation Loss: {history['val_loss'][-1]:.4f}
    • Best Validation Loss: {np.min(history['val_loss']):.4f}
    • Best Epoch: {np.argmin(history['val_loss']) + 1}
    """

    axes[1, 0].text(0.1, 0.9, summary_text, transform=axes[1, 0].transAxes,
                   fontsize=12, verticalalignment='top', fontfamily='monospace',
                   bbox=dict(boxstyle="round,pad=0.3", facecolor="lightblue", alpha=0.7))
    axes[1, 0].set_title('Performance Summary', fontsize=14, fontweight='bold')
    axes[1, 0].axis('off')

    # Loss convergence
    axes[1, 1].plot(history['epoch'], history['train_loss'], label='Train Loss', linewidth=2)
    axes[1, 1].plot(history['epoch'], history['val_loss'], label='Val Loss', linewidth=2)
    axes[1, 1].set_title('Loss Convergence', fontsize=14, fontweight='bold')
    axes[1, 1].set_xlabel('Epoch')
    axes[1, 1].set_ylabel('Loss')
    axes[1, 1].legend()
    axes[1, 1].grid(True, alpha=0.3)

    # Security metrics table
    if security_metrics:
        latest_security = security_metrics[-1]
        security_data = [
            ['Metric', 'Value'],
            ['Cover Entropy', f"{latest_security['cover_entropy']:.3f}"],
            ['Container Entropy', f"{latest_security['container_entropy']:.3f}"],
            ['Correlation', f"{latest_security['cover_container_correlation']:.4f}"],
            ['NPCR', f"{latest_security['npcr']:.1f}%"],
            ['UACI', f"{latest_security['uaci']:.2f}%"],
            ['Histogram Similarity', f"{latest_security['histogram_similarity']:.3f}"]
        ]

        axes[1, 2].axis('off')
        table = axes[1, 2].table(cellText=security_data, loc='center', cellLoc='center')
        table.auto_set_font_size(False)
        table.set_fontsize(10)
        table.scale(1, 2)
        axes[1, 2].set_title('Final Security Metrics', fontsize=14, fontweight='bold', pad=20)

    plt.tight_layout()

    # Save locally
    local_path = os.path.join(save_dir_local, 'final_comprehensive_analysis.png')
    plt.savefig(local_path, dpi=150, bbox_inches='tight')

    # Save to Google Drive
    drive_path = os.path.join(save_dir_drive, 'final_comprehensive_analysis.png')
    save_to_drive(local_path, drive_path)

    plt.close()

# Generate final analysis plots
create_final_analysis_plots(history, security_metrics, final_results, save_dir_local)

# ✅ Save all results to Google Drive
final_save_path_local = os.path.join(save_dir_local, 'deepcrypto_final_results.pth')
final_save_path_drive = os.path.join(save_dir_drive, 'deepcrypto_final_results.pth')

torch.save({
    'epoch': len(history['epoch']),
    'encoder_state_dict': encoder.state_dict(),
    'decoder_state_dict': decoder.state_dict(),
    'mixer_state_dict': mixer.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
    'scheduler_state_dict': scheduler.state_dict(),
    'history': history,
    'security_metrics': security_metrics,
    'final_results': final_results,
    'config': {
        'image_size': IMAGE_SIZE,
        'batch_size': BATCH_SIZE,
        'lambda_cover': LAMBDA_COVER,
        'lambda_secret': LAMBDA_SECRET
    }
}, final_save_path_local)

# Copy to Google Drive
save_to_drive(final_save_path_local, final_save_path_drive)

# Save history as CSV for further analysis
history_df = pd.DataFrame(history)
csv_local = os.path.join(save_dir_local, 'training_history.csv')
csv_drive = os.path.join(save_dir_drive, 'training_history.csv')
history_df.to_csv(csv_local, index=False)
save_to_drive(csv_local, csv_drive)

if security_metrics:
    security_df = pd.DataFrame(security_metrics)
    sec_csv_local = os.path.join(save_dir_local, 'security_metrics.csv')
    sec_csv_drive = os.path.join(save_dir_drive, 'security_metrics.csv')
    security_df.to_csv(sec_csv_local, index=False)
    save_to_drive(sec_csv_local, sec_csv_drive)

print(f"\n🎯 All results saved to Google Drive: {save_dir_drive}")
print("📊 Comprehensive analysis completed!")
print("🔥 DeepCrypto implementation successful!")

# Display final results
print("\n" + "="*80)
print("FINAL RESULTS SUMMARY")
print("="*80)
print(f"Image Resolution: {IMAGE_SIZE}x{IMAGE_SIZE}")
print(f"Cover Image Quality: PSNR = {final_results['psnr_cover']:.2f} dB, SSIM = {final_results['ssim_cover']:.4f}")
print(f"Secret Recovery: PSNR = {final_results['psnr_secret']:.2f} dB, SSIM = {final_results['ssim_secret']:.4f}")
print(f"Final Validation Loss: {history['val_loss'][-1]:.4f}")
print(f"Security Analysis: {len(security_metrics)} epochs analyzed")
print("="*80)

"""## Display Results"""

# Display saved images
def display_saved_results(save_dir):
    """Display all saved result images"""
    saved_images = glob.glob(os.path.join(save_dir, "*.png"))
    print(f"Found {len(saved_images)} result images")

    for img_path in saved_images[:3]:  # Show first 3 images
        plt.figure(figsize=(15, 10))
        img = Image.open(img_path)
        plt.imshow(img)
        plt.axis('off')
        plt.title(f"Results: {os.path.basename(img_path)}")
        plt.show()

# Display results from Google Drive
print("📁 Displaying results from Google Drive...")
display_saved_results(save_dir_drive)

# Show training curves
plt.figure(figsize=(15, 5))

plt.subplot(1, 2, 1)
plt.plot(history['epoch'], history['psnr_cover'], label='Cover PSNR', linewidth=3)
plt.plot(history['epoch'], history['psnr_secret'], label='Secret PSNR', linewidth=3)
plt.title('PSNR Training Progress', fontsize=14, fontweight='bold')
plt.xlabel('Epoch')
plt.ylabel('PSNR (dB)')
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.plot(history['epoch'], history['train_loss'], label='Training Loss', linewidth=2)
plt.plot(history['epoch'], history['val_loss'], label='Validation Loss', linewidth=2)
plt.title('Loss Convergence', fontsize=14, fontweight='bold')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print("\n✅ Training completed successfully!")
print(f"📁 Local results saved in: {save_dir_local}")
print(f"📁 Google Drive results saved in: {save_dir_drive}")
print("🚀 You can now use the trained model for inference!")

# ✅ Final confirmation
print(f"\n🎉 ALL FILES SAVED TO GOOGLE DRIVE!")
print(f"📍 Location: /content/drive/MyDrive/deepcrypto_results/deepcrypto_enhanced_{timestamp}/")
print("📊 You can access these files anytime from your Google Drive!")

# Comprehensive Visualization Package for DeepCrypto
import torch
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from math import pi
import os
from IPython.display import display, Image, HTML

# Comprehensive Results Analysis and Visualization
print("\n" + "="*80)
print("CREATING COMPREHENSIVE RESULT ANALYSIS GRAPHS")
print("="*80)

def create_comprehensive_analysis(history, security_metrics, final_results):
    """Create all requested analysis graphs"""

    # Create figure with subplots
    fig = plt.figure(figsize=(25, 20))

    # 1. PSNR Evolution During Training
    plt.subplot(3, 3, 1)
    plt.plot(history['epoch'], history['psnr_cover'], 'b-', linewidth=3, label='Cover PSNR', alpha=0.8, marker='o', markersize=4)
    plt.plot(history['epoch'], history['psnr_secret'], 'r-', linewidth=3, label='Secret PSNR', alpha=0.8, marker='s', markersize=4)
    plt.title('PSNR Evolution During Training', fontsize=16, fontweight='bold', pad=20)
    plt.xlabel('Epoch', fontsize=12)
    plt.ylabel('PSNR (dB)', fontsize=12)
    plt.legend(fontsize=11)
    plt.grid(True, alpha=0.3)
    plt.ylim(bottom=0)

    # 2. SSIM Evolution During Training
    plt.subplot(3, 3, 2)
    plt.plot(history['epoch'], history['ssim_cover'], 'g-', linewidth=3, label='Cover SSIM', alpha=0.8, marker='^', markersize=4)
    plt.plot(history['epoch'], history['ssim_secret'], 'm-', linewidth=3, label='Secret SSIM', alpha=0.8, marker='d', markersize=4)
    plt.title('SSIM Evolution During Training', fontsize=16, fontweight='bold', pad=20)
    plt.xlabel('Epoch', fontsize=12)
    plt.ylabel('SSIM', fontsize=12)
    plt.legend(fontsize=11)
    plt.grid(True, alpha=0.3)
    plt.ylim(0, 1)

    # 3. Security and Entropy Evolution
    plt.subplot(3, 3, 3)
    if security_metrics:
        epochs = [m['epoch'] for m in security_metrics]
        cover_entropy = [m['cover_entropy'] for m in security_metrics]
        container_entropy = [m['container_entropy'] for m in security_metrics]
        correlation = [m['cover_container_correlation'] for m in security_metrics]

        plt.plot(epochs, cover_entropy, 'c-', linewidth=3, label='Cover Entropy', marker='o', markersize=4)
        plt.plot(epochs, container_entropy, 'y-', linewidth=3, label='Container Entropy', marker='s', markersize=4)
        plt.plot(epochs, correlation, 'k-', linewidth=2, label='Correlation', alpha=0.7, linestyle='--')

        plt.title('Security & Entropy Evolution', fontsize=16, fontweight='bold', pad=20)
        plt.xlabel('Epoch', fontsize=12)
        plt.ylabel('Values', fontsize=12)
        plt.legend(fontsize=11)
        plt.grid(True, alpha=0.3)

    # 4. Security Matrix Radar Chart
    plt.subplot(3, 3, 4)
    if security_metrics and len(security_metrics) > 0:
        latest_security = security_metrics[-1]

        # Security metrics for radar chart
        categories = ['Entropy\nDifference', 'Correlation', 'NPCR', 'Histogram\nSimilarity', 'UACI']

        # Calculate values (normalized where appropriate)
        entropy_diff = abs(latest_security['container_entropy'] - latest_security['cover_entropy'])
        correlation_val = 1 - abs(latest_security['cover_container_correlation'])
        npcr_val = latest_security['npcr'] / 100  # Normalize to 0-1
        hist_similarity = latest_security['histogram_similarity']
        uaci_val = 1 - (latest_security['uaci'] / 50)  # Normalize (assuming max 50%)

        values = [entropy_diff, correlation_val, npcr_val, hist_similarity, uaci_val]

        # Complete the circle
        values += values[:1]
        categories_radar = categories + [categories[0]]

        angles = np.linspace(0, 2*np.pi, len(categories_radar), endpoint=True).tolist()

        ax = plt.subplot(3, 3, 4, polar=True)
        ax.plot(angles, values, 'o-', linewidth=2, label='Security Metrics', color='red')
        ax.fill(angles, values, alpha=0.25, color='red')
        ax.set_thetagrids(np.degrees(angles[:-1]), categories_radar[:-1])
        ax.set_ylim(0, 1)
        ax.set_title('Security Matrix Radar Chart', fontsize=16, fontweight='bold', pad=20)
        ax.grid(True)
        plt.legend(loc='upper right', bbox_to_anchor=(1.3, 1.0))

    # 5. Performance Matrix Bar Chart
    plt.subplot(3, 3, 5)
    metrics = ['Cover PSNR', 'Secret PSNR', 'Cover SSIM', 'Secret SSIM']
    values = [
        final_results['psnr_cover'],
        final_results['psnr_secret'],
        final_results['ssim_cover'],
        final_results['ssim_secret']
    ]

    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728']
    bars = plt.bar(metrics, values, color=colors, alpha=0.7, edgecolor='black', linewidth=1.5)

    # Add value labels on bars
    for bar, value in zip(bars, values):
        plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                f'{value:.2f}', ha='center', va='bottom', fontsize=11, fontweight='bold')

    plt.title('Final Performance Metrics', fontsize=16, fontweight='bold', pad=20)
    plt.ylabel('Values', fontsize=12)
    plt.xticks(rotation=45, ha='right')
    plt.grid(True, alpha=0.3, axis='y')

    # 6. Loss Components Breakdown
    plt.subplot(3, 3, 6)
    loss_components = ['Total Loss', 'Cover Loss', 'Secret Loss']
    final_losses = [
        history['val_loss'][-1],
        history['val_cover_loss'][-1],
        history['val_secret_loss'][-1]
    ]

    colors_loss = ['#ff6b6b', '#4ecdc4', '#45b7d1']
    bars_loss = plt.bar(loss_components, final_losses, color=colors_loss, alpha=0.7, edgecolor='black', linewidth=1.5)

    # Add value labels
    for bar, value in zip(bars_loss, final_losses):
        plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001,
                f'{value:.4f}', ha='center', va='bottom', fontsize=11, fontweight='bold')

    plt.title('Final Loss Components', fontsize=16, fontweight='bold', pad=20)
    plt.ylabel('Loss Value', fontsize=12)
    plt.xticks(rotation=45, ha='right')
    plt.grid(True, alpha=0.3, axis='y')

    # 7. Training vs Validation Loss
    plt.subplot(3, 3, 7)
    plt.plot(history['epoch'], history['train_loss'], 'navy', linewidth=2, label='Training Loss', alpha=0.8)
    plt.plot(history['epoch'], history['val_loss'], 'crimson', linewidth=2, label='Validation Loss', alpha=0.8)
    plt.title('Training vs Validation Loss', fontsize=16, fontweight='bold', pad=20)
    plt.xlabel('Epoch', fontsize=12)
    plt.ylabel('Loss', fontsize=12)
    plt.legend(fontsize=11)
    plt.grid(True, alpha=0.3)
    plt.yscale('log')

    # 8. Security Metrics Comparison
    plt.subplot(3, 3, 8)
    if security_metrics and len(security_metrics) > 0:
        latest = security_metrics[-1]
        security_metrics_names = ['Cover Entropy', 'Container Entropy', 'NPCR (%)', 'UACI (%)']
        security_values = [
            latest['cover_entropy'],
            latest['container_entropy'],
            latest['npcr'],
            latest['uaci']
        ]

        colors_sec = ['#8c564b', '#e377c2', '#7f7f7f', '#bcbd22']
        bars_sec = plt.bar(security_metrics_names, security_values, color=colors_sec, alpha=0.7, edgecolor='black', linewidth=1.5)

        # Add value labels
        for bar, value in zip(bars_sec, security_values):
            plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                    f'{value:.2f}', ha='center', va='bottom', fontsize=11, fontweight='bold')

        plt.title('Final Security Metrics', fontsize=16, fontweight='bold', pad=20)
        plt.ylabel('Values', fontsize=12)
        plt.xticks(rotation=45, ha='right')
        plt.grid(True, alpha=0.3, axis='y')

    # 9. Learning Rate Schedule
    plt.subplot(3, 3, 9)
    plt.plot(history['epoch'], history['learning_rate'], 'purple', linewidth=3, alpha=0.8)
    plt.title('Learning Rate Schedule', fontsize=16, fontweight='bold', pad=20)
    plt.xlabel('Epoch', fontsize=12)
    plt.ylabel('Learning Rate', fontsize=12)
    plt.grid(True, alpha=0.3)
    plt.yscale('log')

    plt.tight_layout(pad=4.0)

    # Save the comprehensive analysis
    local_path = os.path.join(save_dir_local, 'comprehensive_analysis_all_graphs.png')
    drive_path = os.path.join(save_dir_drive, 'comprehensive_analysis_all_graphs.png')

    plt.savefig(local_path, dpi=300, bbox_inches='tight', facecolor='white')
    save_to_drive(local_path, drive_path)

    plt.show()

    return fig

# Create individual specialized plots
def create_individual_analysis_plots(history, security_metrics, final_results):
    """Create individual high-quality analysis plots"""

    # 1. PSNR Evolution (Individual)
    plt.figure(figsize=(12, 8))
    plt.plot(history['epoch'], history['psnr_cover'], 'b-', linewidth=4, label='Cover PSNR', alpha=0.9)
    plt.plot(history['epoch'], history['psnr_secret'], 'r-', linewidth=4, label='Secret PSNR', alpha=0.9)
    plt.title('PSNR Evolution During Training', fontsize=18, fontweight='bold', pad=20)
    plt.xlabel('Epoch', fontsize=14)
    plt.ylabel('PSNR (dB)', fontsize=14)
    plt.legend(fontsize=13)
    plt.grid(True, alpha=0.3)
    plt.ylim(bottom=0)

    # Add final value annotations
    plt.annotate(f'Final: {final_results["psnr_cover"]:.2f} dB',
                xy=(history['epoch'][-1], history['psnr_cover'][-1]),
                xytext=(10, 10), textcoords='offset points',
                bbox=dict(boxstyle='round,pad=0.3', facecolor='lightblue', alpha=0.7),
                fontsize=11)

    plt.annotate(f'Final: {final_results["psnr_secret"]:.2f} dB',
                xy=(history['epoch'][-1], history['psnr_secret'][-1]),
                xytext=(10, 10), textcoords='offset points',
                bbox=dict(boxstyle='round,pad=0.3', facecolor='lightcoral', alpha=0.7),
                fontsize=11)

    local_path = os.path.join(save_dir_local, 'psnr_evolution_individual.png')
    drive_path = os.path.join(save_dir_drive, 'psnr_evolution_individual.png')
    plt.savefig(local_path, dpi=300, bbox_inches='tight')
    save_to_drive(local_path, drive_path)
    plt.show()

    # 2. SSIM Evolution (Individual)
    plt.figure(figsize=(12, 8))
    plt.plot(history['epoch'], history['ssim_cover'], 'g-', linewidth=4, label='Cover SSIM', alpha=0.9)
    plt.plot(history['epoch'], history['ssim_secret'], 'm-', linewidth=4, label='Secret SSIM', alpha=0.9)
    plt.title('SSIM Evolution During Training', fontsize=18, fontweight='bold', pad=20)
    plt.xlabel('Epoch', fontsize=14)
    plt.ylabel('SSIM', fontsize=14)
    plt.legend(fontsize=13)
    plt.grid(True, alpha=0.3)
    plt.ylim(0, 1)

    # Add final value annotations
    plt.annotate(f'Final: {final_results["ssim_cover"]:.4f}',
                xy=(history['epoch'][-1], history['ssim_cover'][-1]),
                xytext=(10, 10), textcoords='offset points',
                bbox=dict(boxstyle='round,pad=0.3', facecolor='lightgreen', alpha=0.7),
                fontsize=11)

    plt.annotate(f'Final: {final_results["ssim_secret"]:.4f}',
                xy=(history['epoch'][-1], history['ssim_secret'][-1]),
                xytext=(10, 10), textcoords='offset points',
                bbox=dict(boxstyle='round,pad=0.3', facecolor='plum', alpha=0.7),
                fontsize=11)

    local_path = os.path.join(save_dir_local, 'ssim_evolution_individual.png')
    drive_path = os.path.join(save_dir_drive, 'ssim_evolution_individual.png')
    plt.savefig(local_path, dpi=300, bbox_inches='tight')
    save_to_drive(local_path, drive_path)
    plt.show()

    # 3. Security Metrics Radar Chart (Enhanced)
    if security_metrics and len(security_metrics) > 0:
        plt.figure(figsize=(10, 10))
        latest_security = security_metrics[-1]

        categories = ['Entropy\nDifference', 'Low\nCorrelation', 'High NPCR',
                     'Histogram\nDivergence', 'High UACI']

        # Calculate normalized security metrics (higher is better for security)
        entropy_diff = min(abs(latest_security['container_entropy'] - latest_security['cover_entropy']) * 5, 1.0)
        low_correlation = 1 - abs(latest_security['cover_container_correlation'])
        high_npcr = latest_security['npcr'] / 100
        hist_divergence = 1 - latest_security['histogram_similarity']
        high_uaci = min(latest_security['uaci'] / 50, 1.0)

        values = [entropy_diff, low_correlation, high_npcr, hist_divergence, high_uaci]
        values += values[:1]  # Complete the circle

        angles = np.linspace(0, 2*np.pi, len(categories), endpoint=False).tolist()
        angles += angles[:1]

        ax = plt.subplot(111, polar=True)
        ax.plot(angles, values, 'o-', linewidth=3, label='Security Level', color='darkred')
        ax.fill(angles, values, alpha=0.25, color='darkred')

        ax.set_thetagrids(np.degrees(angles[:-1]), categories)
        ax.set_ylim(0, 1)
        ax.set_title('Security Analysis Radar Chart\n(Higher Values = Better Security)',
                    fontsize=16, fontweight='bold', pad=30)
        ax.grid(True)
        plt.legend(loc='upper right', bbox_to_anchor=(1.3, 1.0), fontsize=12)

        # Add metric values as text
        for angle, value, category in zip(angles[:-1], values[:-1], categories):
            ax.text(angle, 1.1, f'{value:.2f}', ha='center', va='center',
                   fontsize=10, fontweight='bold',
                   bbox=dict(boxstyle='round,pad=0.3', facecolor='yellow', alpha=0.7))

        local_path = os.path.join(save_dir_local, 'security_radar_enhanced.png')
        drive_path = os.path.join(save_dir_drive, 'security_radar_enhanced.png')
        plt.savefig(local_path, dpi=300, bbox_inches='tight')
        save_to_drive(local_path, drive_path)
        plt.show()

    # 4. Performance Matrix Bar Chart (Enhanced)
    plt.figure(figsize=(14, 8))

    metrics_groups = ['Cover Image', 'Secret Recovery']
    psnr_values = [final_results['psnr_cover'], final_results['psnr_secret']]
    ssim_values = [final_results['ssim_cover'], final_results['ssim_secret']]

    x = np.arange(len(metrics_groups))
    width = 0.35

    fig, ax = plt.subplots(figsize=(14, 8))
    bars1 = ax.bar(x - width/2, psnr_values, width, label='PSNR (dB)', color='skyblue', edgecolor='navy', linewidth=2)
    bars2 = ax.bar(x + width/2, ssim_values, width, label='SSIM', color='lightcoral', edgecolor='darkred', linewidth=2)

    ax.set_xlabel('Metric Categories', fontsize=14)
    ax.set_ylabel('Values', fontsize=14)
    ax.set_title('Performance Matrix: Final Results', fontsize=18, fontweight='bold', pad=20)
    ax.set_xticks(x)
    ax.set_xticklabels(metrics_groups)
    ax.legend(fontsize=12)
    ax.grid(True, alpha=0.3, axis='y')

    # Add value labels on bars
    def autolabel(bars):
        for bar in bars:
            height = bar.get_height()
            ax.annotate(f'{height:.2f}',
                       xy=(bar.get_x() + bar.get_width() / 2, height),
                       xytext=(0, 3),
                       textcoords="offset points",
                       ha='center', va='bottom', fontsize=11, fontweight='bold')

    autolabel(bars1)
    autolabel(bars2)

    plt.tight_layout()
    local_path = os.path.join(save_dir_local, 'performance_matrix_enhanced.png')
    drive_path = os.path.join(save_dir_drive, 'performance_matrix_enhanced.png')
    plt.savefig(local_path, dpi=300, bbox_inches='tight')
    save_to_drive(local_path, drive_path)
    plt.show()

# Generate all analysis plots
print("📊 Generating comprehensive analysis graphs...")

# Create comprehensive analysis
comprehensive_fig = create_comprehensive_analysis(history, security_metrics, final_results)

# Create individual high-quality plots
create_individual_analysis_plots(history, security_metrics, final_results)

print("✅ All analysis graphs created and saved!")
print(f"📁 Local directory: {save_dir_local}")
print(f"📁 Google Drive directory: {save_dir_drive}")

# Print final summary
print("\n" + "="*80)
print("FINAL PERFORMANCE SUMMARY")
print("="*80)
print(f"🏆 Cover Image Quality:")
print(f"   • PSNR: {final_results['psnr_cover']:.2f} dB")
print(f"   • SSIM: {final_results['ssim_cover']:.4f}")

print(f"🔐 Secret Recovery Quality:")
print(f"   • PSNR: {final_results['psnr_secret']:.2f} dB")
print(f"   • SSIM: {final_results['ssim_secret']:.4f}")

if security_metrics and len(security_metrics) > 0:
    latest_sec = security_metrics[-1]
    print(f"🛡️  Security Analysis:")
    print(f"   • Cover Entropy: {latest_sec['cover_entropy']:.3f}")
    print(f"   • Container Entropy: {latest_sec['container_entropy']:.3f}")
    print(f"   • Correlation: {latest_sec['cover_container_correlation']:.6f}")
    print(f"   • NPCR: {latest_sec['npcr']:.2f}%")
    print(f"   • UACI: {latest_sec['uaci']:.2f}%")

print(f"📈 Training Statistics:")
print(f"   • Total Epochs: {len(history['epoch'])}")
print(f"   • Final Validation Loss: {history['val_loss'][-1]:.4f}")
print(f"   • Best Validation Loss: {min(history['val_loss']):.4f}")
print("="*80)



import matplotlib.pyplot as plt
import numpy as np

# Data from your training log - 47 epochs
epochs = list(range(1, 48))

# 1. Training and Validation Loss
train_loss = [
    1.0200, 0.4626, 0.3856, 0.3640, 0.3187, 0.3009, 0.2756, 0.2512, 0.2524, 0.2410,
    0.2410, 0.1831, 0.1659, 0.1570, 0.1574, 0.1450, 0.1392, 0.1336, 0.1313, 0.1278,
    0.1248, 0.1236, 0.1205, 0.1167, 0.1112, 0.1135, 0.1104, 0.1074, 0.1077, 0.1026,
    0.0969, 0.1033, 0.0969, 0.0963, 0.0914, 0.0896, 0.0880, 0.0872, 0.0858, 0.0825,
    0.0835, 0.0812, 0.0788, 0.0769, 0.0763, 0.0750, 0.0750
]

val_loss = [
    0.5691, 0.4758, 0.4578, 0.4943, 0.3957, 0.6773, 0.3140, 0.2474, 0.2637, 0.2411,
    0.2064, 0.2274, 0.1552, 0.1937, 0.1349, 0.1249, 0.1526, 0.2178, 0.1329, 0.1081,
    0.1481, 0.1107, 0.1387, 0.1093, 0.1723, 0.1940, 0.1380, 0.1462, 0.1164, 0.1052,
    0.1193, 0.1216, 0.0879, 0.1015, 0.0952, 0.0811, 0.0762, 0.1075, 0.1147, 0.0969,
    0.1060, 0.1041, 0.0844, 0.0858, 0.1007, 0.0813, 0.0915
]

# 2. Component Losses (Cover and Secret Loss)
cover_loss = [
    0.2303, 0.1099, 0.0892, 0.0849, 0.0746, 0.0686, 0.0629, 0.0560, 0.0558, 0.0541,
    0.0549, 0.0592, 0.0552, 0.0539, 0.0540, 0.0519, 0.0524, 0.0496, 0.0495, 0.0486,
    0.0479, 0.0471, 0.0459, 0.0452, 0.0444, 0.0448, 0.0443, 0.0442, 0.0442, 0.0436,
    0.0413, 0.0425, 0.0415, 0.0413, 0.0401, 0.0398, 0.0391, 0.0387, 0.0389, 0.0383,
    0.0384, 0.0378, 0.0374, 0.0371, 0.0369, 0.0367, 0.0369
]

secret_loss = [
    0.1579, 0.0705, 0.0593, 0.0558, 0.0488, 0.0465, 0.0425, 0.0391, 0.0393, 0.0374,
    0.0372, 0.0248, 0.0222, 0.0206, 0.0207, 0.0186, 0.0174, 0.0168, 0.0164, 0.0158,
    0.0154, 0.0153, 0.0149, 0.0143, 0.0134, 0.0138, 0.0132, 0.0126, 0.0127, 0.0118,
    0.0111, 0.0122, 0.0111, 0.0110, 0.0102, 0.0100, 0.0098, 0.0097, 0.0094, 0.0088,
    0.0090, 0.0087, 0.0083, 0.0080, 0.0079, 0.0077, 0.0076
]

# Create figure with two subplots side by side
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# ========== LEFT PLOT: Training and Validation Loss (Figure 4) ==========
axes[0].plot(epochs, train_loss, 'b-', linewidth=2.5, label='Training Loss')
axes[0].plot(epochs, val_loss, 'r-', linewidth=2.5, label='Validation Loss')

# Mark the best validation loss at epoch 36
best_epoch = 36  # Your best model is at epoch 36
best_val_loss = 0.0762
axes[0].scatter(best_epoch, best_val_loss, color='green', s=150, zorder=5,
                edgecolor='black', linewidth=2, label=f'Best Model (Epoch {best_epoch})')

# Add annotation for best model
axes[0].annotate(f'Best Model\n(Epoch {best_epoch})',
                 xy=(best_epoch, best_val_loss),
                 xytext=(best_epoch+3, best_val_loss+0.1),
                 arrowprops=dict(facecolor='green', shrink=0.05, width=1.5),
                 fontsize=11, fontweight='bold', color='green')

axes[0].set_xlabel('Epoch', fontsize=13, fontweight='bold')
axes[0].set_ylabel('Loss', fontsize=13, fontweight='bold')
axes[0].set_title('(a) Training and Validation Loss Convergence', fontsize=14, fontweight='bold', pad=15)
axes[0].grid(True, alpha=0.3, linestyle='--')
axes[0].legend(fontsize=11, loc='upper right')
axes[0].set_ylim(0, 0.8)
axes[0].tick_params(axis='both', which='major', labelsize=11)

# Add minor grid
axes[0].minorticks_on()
axes[0].grid(which='minor', alpha=0.2, linestyle=':')

# ========== RIGHT PLOT: Component Losses (Figure 11) ==========
axes[1].plot(epochs, cover_loss, 'b-', linewidth=2.5, label='Cover Loss (λ_cover = 1.0)')
axes[1].plot(epochs, secret_loss, 'r-', linewidth=2.5, label='Secret Loss (λ_secret = 5.0)')

# Highlight the prioritization of secret loss
axes[1].fill_between(epochs, 0, secret_loss, alpha=0.1, color='red')
axes[1].fill_between(epochs, 0, cover_loss, alpha=0.1, color='blue')

# Add annotation for loss weighting
axes[1].annotate('Prioritized Secret Recovery\n(λ_secret = 5 × λ_cover)',
                 xy=(25, 0.015), xytext=(35, 0.08),
                 arrowprops=dict(facecolor='red', shrink=0.05, width=1.5),
                 fontsize=11, fontweight='bold', color='red',
                 bbox=dict(boxstyle="round,pad=0.3", facecolor="white", alpha=0.8))

axes[1].set_xlabel('Epoch', fontsize=13, fontweight='bold')
axes[1].set_ylabel('Loss', fontsize=13, fontweight='bold')
axes[1].set_title('(b) Component Losses: Cover vs Secret', fontsize=14, fontweight='bold', pad=15)
axes[1].grid(True, alpha=0.3, linestyle='--')
axes[1].legend(fontsize=11, loc='upper right')
axes[1].tick_params(axis='both', which='major', labelsize=11)

# Add minor grid
axes[1].minorticks_on()
axes[1].grid(which='minor', alpha=0.2, linestyle=':')

# Adjust layout and save
plt.tight_layout()
plt.subplots_adjust(wspace=0.25)  # Space between subplots

# Save the combined figure
plt.savefig('figure4_combined_training_curves.png', dpi=300, bbox_inches='tight', facecolor='white')
plt.show()

# Print summary for your paper
print("="*60)
print("TRAINING SUMMARY FOR YOUR PAPER:")
print("="*60)
print(f"Total Training Epochs: {len(epochs)}")
print(f"Best Model: Epoch {best_epoch} (Validation Loss: {best_val_loss:.4f})")
print(f"Final Training Loss (Epoch {epochs[-1]}): {train_loss[-1]:.4f}")
print(f"Final Validation Loss: {val_loss[-1]:.4f}")
print(f"Final Cover Loss: {cover_loss[-1]:.4f}")
print(f"Final Secret Loss: {secret_loss[-1]:.4f}")
print(f"Cover PSNR: 22.20 dB")
print(f"Secret PSNR: 32.77 dB")
print(f"Cover SSIM: 0.9091")
print(f"Secret SSIM: 0.9723")
print("="*60)
print(f"\n✅ Combined figure saved as: 'figure4_combined_training_curves.png'")
print("📍 Use this as Figure 4 in your paper")

import matplotlib.pyplot as plt
import numpy as np

# Data from your training log
epochs = list(range(1, 48))

# Loss data (same as before)
train_loss = [1.0200, 0.4626, 0.3856, 0.3640, 0.3187, 0.3009, 0.2756, 0.2512, 0.2524, 0.2410,
              0.2410, 0.1831, 0.1659, 0.1570, 0.1574, 0.1450, 0.1392, 0.1336, 0.1313, 0.1278,
              0.1248, 0.1236, 0.1205, 0.1167, 0.1112, 0.1135, 0.1104, 0.1074, 0.1077, 0.1026,
              0.0969, 0.1033, 0.0969, 0.0963, 0.0914, 0.0896, 0.0880, 0.0872, 0.0858, 0.0825,
              0.0835, 0.0812, 0.0788, 0.0769, 0.0763, 0.0750, 0.0750]

val_loss = [0.5691, 0.4758, 0.4578, 0.4943, 0.3957, 0.6773, 0.3140, 0.2474, 0.2637, 0.2411,
            0.2064, 0.2274, 0.1552, 0.1937, 0.1349, 0.1249, 0.1526, 0.2178, 0.1329, 0.1081,
            0.1481, 0.1107, 0.1387, 0.1093, 0.1723, 0.1940, 0.1380, 0.1462, 0.1164, 0.1052,
            0.1193, 0.1216, 0.0879, 0.1015, 0.0952, 0.0811, 0.0762, 0.1075, 0.1147, 0.0969,
            0.1060, 0.1041, 0.0844, 0.0858, 0.1007, 0.0813, 0.0915]

cover_loss = [0.2303, 0.1099, 0.0892, 0.0849, 0.0746, 0.0686, 0.0629, 0.0560, 0.0558, 0.0541,
              0.0549, 0.0592, 0.0552, 0.0539, 0.0540, 0.0519, 0.0524, 0.0496, 0.0495, 0.0486,
              0.0479, 0.0471, 0.0459, 0.0452, 0.0444, 0.0448, 0.0443, 0.0442, 0.0442, 0.0436,
              0.0413, 0.0425, 0.0415, 0.0413, 0.0401, 0.0398, 0.0391, 0.0387, 0.0389, 0.0383,
              0.0384, 0.0378, 0.0374, 0.0371, 0.0369, 0.0367, 0.0369]

secret_loss = [0.1579, 0.0705, 0.0593, 0.0558, 0.0488, 0.0465, 0.0425, 0.0391, 0.0393, 0.0374,
               0.0372, 0.0248, 0.0222, 0.0206, 0.0207, 0.0186, 0.0174, 0.0168, 0.0164, 0.0158,
               0.0154, 0.0153, 0.0149, 0.0143, 0.0134, 0.0138, 0.0132, 0.0126, 0.0127, 0.0118,
               0.0111, 0.0122, 0.0111, 0.0110, 0.0102, 0.0100, 0.0098, 0.0097, 0.0094, 0.0088,
               0.0090, 0.0087, 0.0083, 0.0080, 0.0079, 0.0077, 0.0076]

# Create professional figure
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Left plot: Training and Validation Loss
axes[0].plot(epochs, train_loss, 'b-', linewidth=2, label='Training Loss')
axes[0].plot(epochs, val_loss, 'r-', linewidth=2, label='Validation Loss')
axes[0].set_xlabel('Epoch', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Loss', fontsize=12, fontweight='bold')
axes[0].set_title('(a) Training Convergence', fontsize=13, fontweight='bold')
axes[0].grid(True, alpha=0.3, linestyle='--')
axes[0].legend(fontsize=11)
axes[0].set_ylim(0, 0.8)

# Right plot: Component Losses
axes[1].plot(epochs, cover_loss, 'b-', linewidth=2, label=f'Cover Loss (λ={1.0})')
axes[1].plot(epochs, secret_loss, 'r-', linewidth=2, label=f'Secret Loss (λ={5.0})')
axes[1].set_xlabel('Epoch', fontsize=12, fontweight='bold')
axes[1].set_ylabel('Loss', fontsize=12, fontweight='bold')
axes[1].set_title('(b) Component Losses', fontsize=13, fontweight='bold')
axes[1].grid(True, alpha=0.3, linestyle='--')
axes[1].legend(fontsize=11)

# Adjust layout
plt.tight_layout()
plt.subplots_adjust(wspace=0.3)

# Save
plt.savefig('figure4_scientific_report.png', dpi=300, bbox_inches='tight')
plt.show()

print("✅ Scientific report figure saved as 'figure4_scientific_report.png'")

